"""
Pydantic Models for Document Processing with OpenAI Batch API.

This module defines the data structures used throughout the document processing application.
These models ensure type safety and data validation for:
1.  Constructing requests for the OpenAI Batch API.
2.  Parsing the responses received from the OpenAI Batch API.
3.  Handling the application's internal logic, such as data extraction and comparison.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


# --- Pydantic Models for OpenAI Batch API Request Creation ---
# These models are used to structure the data sent to the OpenAI Batch API.

class ChatRequestBody(BaseModel):
    """
    Defines the structure of the 'body' for a chat completion request.

    This model is nested within the `BatchRequest` model and contains the core
    details of the prompt and parameters for the OpenAI model.
    """
    model: str = "gpt-4o"
    messages: list[dict[str, str]]
    temperature: float = 0.0
    tools: list[dict[str, Any]] | None = None
    tool_choice: str | None = None


class BatchRequest(BaseModel):
    """
    Represents a single request object for the OpenAI Batch API.

    Each instance of this model corresponds to one line in the JSONL file
    that will be uploaded to OpenAI for batch processing.
    """
    custom_id: str = Field(
        ...,
        description="A unique identifier for the request to match it with the response. "
                    "This is crucial for tracking individual requests within a batch.",
    )
    method: str = Field(
        "POST",
        description="The HTTP method, which is always POST for chat completions.",
    )
    url: str = Field(
        "/v1/chat/completions",
        description="The API endpoint for the chat completion request.",
    )
    body: ChatRequestBody


# --- Pydantic Models for Processing OpenAI Batch API Responses ---
# These models are used to parse the JSONL output file generated by a completed batch job.

class FunctionCall(BaseModel):
    """
    Represents the function call generated by the model.

    The 'arguments' field contains a JSON string with the data extracted by the model,
    which can be parsed into the `ExtractedData` model.
    """
    arguments: str  # This will be a JSON string representing the extracted data.
    name: str


class ToolCall(BaseModel):
    """
    Represents a tool call made by the model as part of its response.
    """
    id: str
    function: FunctionCall
    type: str


class ResponseMessage(BaseModel):
    """
    The message object within a response choice, containing tool calls.
    """
    tool_calls: list[ToolCall]


class ChatCompletionChoice(BaseModel):
    """
    Defines the structure of a single choice in a chat completion response.
    """
    message: ResponseMessage


class ChatCompletionBody(BaseModel):
    """
    The 'body' of a successful response from the Batch API.

    This model captures the main content of the response for a single request in the batch.
    """
    id: str
    model: str
    choices: list[ChatCompletionChoice]


class ResponseInfo(BaseModel):
    """
    The 'response' object within a batch result line.

    It contains the HTTP status code and the body of the response from the OpenAI API.
    """
    status_code: int
    body: ChatCompletionBody


class BatchResponse(BaseModel):
    """
    Represents a single result line from the OpenAI Batch API output file.

    This is the top-level model for parsing each line of the batch job's output.
    It includes the original custom_id to link the response back to the request.
    """
    id: str
    custom_id: str
    response: ResponseInfo | None = None
    error: dict[str, Any] | None = None


# --- Pydantic Models for Application-Specific Logic ---
# These models are used for handling data within the Azure Function logic.

class ExtractedData(BaseModel):
    """
    The structured data that the OpenAI model is prompted to extract.

    This model is used as a schema for the 'extract_data' function tool,
    ensuring the model's output is in a predictable, structured format.
    """
    extracted_key: str = Field(description="The key extracted from the document text.")
    extracted_value: str = Field(
        description="The value corresponding to the extracted key.",
    )


class ComparisonResult(BaseModel):
    """
    The final output message sent to the queue after processing and comparison.

    This model encapsulates all the relevant information about the processing of a
    single field from a document, including the extracted text, comparison score, and status.
    """
    document_field_id: str = Field(
        ...,
        description="The custom_id from the original request, linking back to the document field.",
    )
    openai_extracted_text: str = Field(
        ...,
        description="The processed text extracted by the OpenAI model.",
    )
    original_text_for_comparison: str = Field(
        ...,
        description="The original text used for the fuzzy comparison.",
    )
    fuzzy_match_score: int = Field(
        ...,
        description="The similarity score (0-100) from the fuzzy comparison.",
    )
    status: str = Field(
        ...,
        description="The outcome of the processing (e.g., 'Processed - High Score', 'Processed - Low Score').",
    )
    error_message: str | None = Field(
        None,
        description="Any error message encountered during processing.",
    )
